export enum CardName {
    ScotiaMomentumVI = 'Stotia Momentum VI',
    ScotiaMomentumV = 'Scotia Momentum V',
    ScotiaMomentumNoFeeV = 'Scotia Momentum No-Fee V',
    ScotiaMomentumMastercard = 'Scotia Momentum Mastercard',
    BMOCashBackWEMC = 'BMO CashBack WE MC',
    BMOCashBackMC = 'BMO CashBack MC',
    CIBCDividendVI = 'CIBC Dividend VI',
    CIBCDividendPlatinumV = 'CIBC Dividend Platinum V',
    CIBCDividentV = 'CIBC Dividend V',
    CIBCCostcoMC = 'CIBC Costco MC',
    RBCCashBackPreferredWEMC = 'RBC CashBack Preferred WE MC',
    RBCCashBackMC = 'RBC Cash Back MC',
    TDCashBackVI = 'TD Cash Back VI',
    TDCashBackV = 'TD Cash Back V',
    AmexSimplyCash = 'Amex SimplyCash',
    AmexSimplyCashPreferred = 'Amex SimplyCash Preferred',
    SimpliiVisa = 'Simplii Visa',
    TangerineMoneyBackMC = 'Thangerine Money-Back MC',
    TangerineWorldMC = 'Tangerine World MC',
    RogersRedWEMC = 'Rogers Red WE MC',
    NeoBaseMC = 'Neo Base MC',
    NeoPremiumMC = 'Neo Premium MC',
    DesjardinsCashBackWEMC ='Desjardins Cash Back WE MC',
    DesjardinsCashBackMC = 'Desjardins Cash Back MC',
    DesjardinsCashBackVisa = 'Desjardins Cash Back Visa',
    MBNASmartCashPlatinumPlusMC = 'MBNA Smart Cash Platinum Plus MC',
    MBNAsmartCashWorldMC = 'MBNA Smart Cash World MC',
    NBCmycreditMC = 'MBC mycredit MC',
    NBCAllureMC = 'NBC Allure MC',
    NBCECHOCashbackMC = 'NBC ECHO Cashback MC'


}